# The data_indices inputs are generated by running the training scripts
# image_path also accepts multiple paths if your livecell_all_images are in different directories
python3 -u ../downstream.py --name figure_2b_spaghetti \
--task segmentation \
--image_path path_to/livecell_all_images \
--data_indices path_to/train_indicies.txt path_to/val_indicies.txt \
--save_dir path_to_save_dir \
--segmentation_model tissuenet_cp3 tissuenet_cp3 cyto3 2D_versatile_he 2D_versatile_he \
--do_convert True False False True False  \
--do_invert False False False False False \
--convert path_to/spaghetti.ckpt \
--coco path_to/livecell_coco_test.json path_to/livecell_coco_train.json path_to/livecell_coco_val.json \

python3 -u ../downstream.py --name figure_2b_cyclegan \
--task segmentation \
--image_path path_to/livecell_all_images \
--data_indices path_to/train_indicies.txt path_to/val_indicies.txt \
--save_dir path_to_save_dir \
--segmentation_model tissuenet_cp3 tissuenet_cp3 cyto3 2D_versatile_he 2D_versatile_he \
--do_convert True False False True False  \
--do_invert False False False False False \
--convert path_to/vanila_cyclegan.ckpt \
--coco path_to/livecell_coco_test.json path_to/livecell_coco_train.json path_to/livecell_coco_val.json \