'''
visualize the feature map generated by ViT-large
'''

import argparse
import torch
import numpy as np
import random
import pytorch_lightning as pl
import torchvision.transforms.v2 as v2
from torchvision.transforms.functional import invert
from utils.dataset import CustomImageDataset, Gfp_Dataset, Vaibility_Dataset
from utils.utils import prep_datasets, loader_data
from utils.utils import image_transform as trans_cycleGAN
from feature_extractors import owkin_features
from downstream import init_cycleGAN, cycleGAN_transform
from transformers import AutoImageProcessor, AutoModel
import matplotlib.pyplot as plt
import os
from tqdm import tqdm
from pycocotools.coco import COCO
from segment import get_mask_per_instance, compute_probabilistic_dice_score
import skimage.transform as st
import timeit
import umap
import tracemalloc

def crop_center(img,cropx,cropy):
    '''
    Centre crop an numpy image
    '''
    y,x = img.shape
    startx = x//2-(cropx//2)
    starty = y//2-(cropy//2)    
    return img[starty:starty+cropy,startx:startx+cropx]

def plot_umap(data, labels, save_dir, exp_name):
    '''
    Plot the umap of the data
    '''
    reducer = umap.UMAP()
    embedding = reducer.fit_transform(data)
    fig, ax = plt.subplots()
    for i, label in enumerate(labels):
        ax.scatter(embedding[i, 0], embedding[i, 1], label=label)
    ax.legend()
    plt.savefig(os.path.join(save_dir, f"umap_{exp_name}.svg"))
    plt.close()

def generate_attn_maps(attn: torch.Tensor, size: int = 256, 
                       threshold: float = 0.6) -> np.ndarray:
    '''
    Process the attention values to generate a heatmap of size x size based on threshold
    '''
    # get the attention except for the cls token
    class_token_attention = attn[:, :, 0, 1:]
    nh = class_token_attention.shape[1]
    # we keep only a certain percentage of the mass according to threshold
    val, idx = torch.sort(class_token_attention.reshape(nh, -1))
    val /= torch.sum(val, dim=1, keepdim=True)
    cumval = torch.cumsum(val, dim=1)
    th_attn = cumval > (1 - threshold)
    idx2 = torch.argsort(idx)
    for head in range(class_token_attention.shape[1]):
        th_attn[head] = th_attn[head][idx2[head]]
    num_patches_side = int(class_token_attention.shape[-1] ** 0.5)
    class_token_attention = th_attn.reshape(1, nh, num_patches_side, num_patches_side).float()
    # average all the head
    class_token_attention = class_token_attention.mean(dim=1)
    attention_map = class_token_attention.view(num_patches_side, num_patches_side).cpu()
    # extrapolate to size x size
    resized_attn = torch.nn.functional.interpolate(attention_map.unsqueeze(0).unsqueeze(0), size=(size, size), 
                                                        mode='bicubic')
    # return a numpy array of size x size (no batch or channel)
    return resized_attn.squeeze(0).squeeze(0).cpu().numpy()

def generate_attn_maps_all(attn: torch.Tensor, size: int = 256) -> np.ndarray:
    '''
    Process the attention values to generate a heatmap of size x size
    '''
    # get the attention except for the cls token
    class_token_attention = attn[:, :, 0, 1:]
    nh = class_token_attention.shape[1]
    num_patches_side = int(class_token_attention.shape[-1] ** 0.5)
    class_token_attention = class_token_attention.reshape(1, nh, num_patches_side, num_patches_side).float()
    class_token_attention = class_token_attention.mean(dim=1)
    attention_map = class_token_attention.view(num_patches_side, num_patches_side).cpu()
    # extrapolate to size x size
    resized_attn = torch.nn.functional.interpolate(attention_map.unsqueeze(0).unsqueeze(0), size=(size, size), 
                                                        mode='bicubic')
    # return a numpy array of size x size (no batch or channel)
    return resized_attn.squeeze(0).squeeze(0).cpu().numpy()

def visualize_feature(feature: list[torch.Tensor], labels: list[str], 
                      img: torch.Tensor, converted_L: list[torch.Tensor], 
                      save_dir: str, img_name: str, exp_name: str):
    '''
    Visualize the class token attention map generated by Phikon (token length = 16x16x3 +1)
    '''
    img_np = np.moveaxis(img.squeeze(0).cpu().numpy(), 0, -1)
    converted_np = [np.moveaxis(converted.squeeze(0).cpu().numpy(), 0, -1) for converted in converted_L[0:1]]
    process_feature_L = []
    for each_feature in feature:
        each_feature_256 = generate_attn_maps(each_feature, size=256)
        process_feature_L.append(each_feature_256)
    fig, ax = plt.subplots(1, len(process_feature_L)+2, figsize=(20, 10))
    ax[0].imshow(img_np)
    ax[0].axis('off')
    ax[0].set_title("Original image")
    ax[1].imshow(converted_np[0])
    ax[1].axis('off')
    ax[1].set_title("SPAGHETTI image")
    for i, each in enumerate(process_feature_L):
        ax[i+2].imshow(img_np)
        im = ax[i+2].imshow(each, cmap='plasma', alpha=0.5)
        ax[i+2].axis('off')
        ax[i+2].set_title(labels[i])
        fig.colorbar(im, fraction=0.046, pad=0.04)
    plt.savefig(os.path.join(save_dir, "visualization", f"feature_{exp_name}_{img_name}.svg"))
    plt.close()

def generate_dice_score(data_loader, feature_extractor, labels: list[str], exp_name: str, 
                        save_dir: str, coco_L: list[str], do_crop: bool = True, do_invert: bool = False):
    '''
    Generate the dice score for the attention map and write to a file
    '''
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    final_dict: dict[str, list[float]] = {x: [] for x in labels}
    final_dict_diff: dict[str, list[float]] = {x: [] for x in labels}
    for img, label in tqdm(data_loader):
        f_path = label[2][0]
        # get the masks
        coco_masks = get_mask_per_instance(coco_L, f_path)
        if do_crop:
            coco_masks = crop_center(coco_masks, 64, 64)
        # binarize the masks
        binary_coco_masks = (coco_masks > 0).astype(np.uint8)
        binary_coco_masks = st.resize(binary_coco_masks, (256,256), order=0, preserve_range=True, anti_aliasing=False)
        # get attn map for each feature extractor
        max_attn_L = []
        attn_map_L = []
        for i, extractor in enumerate(feature_extractor):
            if do_invert:
                attn, _, _, _ = extractor(invert(img), device, train=False)
            else:
                attn, _, _, _ = extractor(img, device, train=False)
            attn_map = generate_attn_maps_all(attn, size=256)
            max_attn = attn_map.max().item()
            max_attn_L.append(max_attn)
            attn_map_L.append(attn_map)
        max_attention = max(max_attn_L)
        for i, each in enumerate(attn_map_L):
            ## compute dice
            # normalized_attn_map = each / max_attention
            normalized_attn_map = each / max_attn_L[i]
            dice = compute_probabilistic_dice_score(normalized_attn_map, binary_coco_masks)
            final_dict[labels[i]].append(dice)
    
    for key, value in final_dict.items():
        with open(os.path.join(save_dir, f"dice_{exp_name}_{key}.txt"), "w") as f:
            f.write("\n".join([str(x) for x in value]))

def generate_visualization(data_loader, feature_extractor, save_dir: str, do_invert = False, 
                           log_time=False):
    '''
    Generate the visualization of the feature map generated by ViT-large
    '''
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    exp_list = ["SPAGHETTI", "Phikon_only"]
    time_dict = {x: [] for x in exp_list}
    feature_dict = {x: [] for x in exp_list}
    memory_dict = {x: [] for x in exp_list}
    cell_type_L = []
    for idx, (img, label) in enumerate(tqdm(data_loader)):
        attn_L = []
        converted_img_L = []
        for i, extractor in enumerate(feature_extractor):
            start = timeit.default_timer()
            tracemalloc.start()
            if do_invert:
                attn, img_processed, converted, features = extractor(img if i == 1 else invert(img), device, train=False)
            else:
                attn, img_processed, converted, features = extractor(img, device, train=False)
            current, peak = tracemalloc.get_traced_memory()
            print(f"Current memory usage is {current / 10**6}MB; Peak was {peak / 10**6}MB")
            tracemalloc.reset_peak()
            tracemalloc.stop()
            stop = timeit.default_timer()
            time_dict[exp_list[i]].append(stop-start)
            converted_img_L.append(converted)
            attn_L.append(attn)
            feature_dict[exp_list[i]].append(features)
            memory_dict[exp_list[i]].append(peak / 10**6)
        cell_type = label[3][0]
        cell_type_L.append(cell_type)
        # plot visualization
        visualize_feature(attn_L, ["SPAGHETTI + Phikon", "Phikon Only"], 
                          img_processed, converted_img_L, save_dir, 
                          f"{cell_type}_{idx}", args.name)
    # generate features
    feature_save = os.path.join(save_dir, "feature_celltype")
    if not os.path.isdir(feature_save):
        os.makedirs(feature_save)
    feature_dict["SPAGHETTI"] = torch.cat(feature_dict["SPAGHETTI"], dim=0).cpu().numpy()
    feature_dict["Phikon_only"] = torch.cat(feature_dict["Phikon_only"], dim=0).cpu().numpy()
    # save the cell type and features
    np.save(os.path.join(feature_save, "cell_type.npy"), np.array(cell_type_L))
    np.save(os.path.join(feature_save, "SPAGHETTI.npy"), feature_dict["SPAGHETTI"])
    np.save(os.path.join(feature_save, "Phikon_only.npy"), feature_dict["Phikon_only"])
    # log the run time for feature extraction using phikon-v2
    if log_time:
        for key, value in time_dict.items():
            with open(os.path.join(save_dir, f"feature_time_in_sec_{key}.txt"), "w") as f:
                f.write("\n".join([str(x) for x in value]))
        for key, value in memory_dict.items():
            with open(os.path.join(save_dir, f"feature_memory_in_MB_{key}.txt"), "w") as f:
                f.write("\n".join([str(x) for x in value]))

def main():
    if args.crop:
        if not args.coco:
            transform = v2.Compose([v2.RandomCrop(size=256), v2.Resize((256,256))])
        else:
            transform = v2.Compose([v2.CenterCrop(size=256), v2.Resize((256,256))])
            coco_L = [COCO(coco) for coco in args.coco]
        transform_L = transform
    else:
        if args.coco:
            coco_L = [COCO(coco) for coco in args.coco]
        transform_L = None
    if args.gfp_data:
        data = Gfp_Dataset(args.image_path[0], transform=None)
    elif args.gfp_data_russian:
        data = Vaibility_Dataset(args.image_path[0], transform=None, return_gfp=True)
    else:
        data = CustomImageDataset(args.image_path, transform=transform_L)
        class_to_idx = data.class_to_idx
        print("Data prep finished. The class to idx is: ", class_to_idx)
        if args.data_indices:
            indices = []
            for each in args.data_indices:
                with open(each, "r") as f:
                    idx = f.readlines()
                    idx = [int(x) for x in idx]
                indices.append(idx)
            _, data = prep_datasets(data, indices)
    total_loader = loader_data(data, batch_size=1)
    print("Data loaded, size: ", len(total_loader))

    # prepare cycleGAN
    process_cycleGAN = trans_cycleGAN(do_augmentation=False, do_cropping=False)

    cycleGAN_gen_ssim = init_cycleGAN(args.ssim)
    convert_to_HE_ssim = lambda x, device: cycleGAN_transform(cycleGAN_gen_ssim, device, process_cycleGAN, x)

    # prepare the feature extractor
    feature_extractor = AutoModel.from_pretrained("owkin/phikon-v2")
    image_processor = AutoImageProcessor.from_pretrained("owkin/phikon-v2")
    feature_ssim = lambda x, device, train: owkin_features(feature_extractor, device, image_processor, x, 
                                                        convert=convert_to_HE_ssim, do_crop=False, train=train, 
                                                        return_x=True, return_attn=True)
    feature_raw = lambda x, device, train: owkin_features(feature_extractor, device, image_processor, x,
                                                        convert=None, do_crop=False, train=train, 
                                                        return_x=True, return_attn=True)
    feature = [feature_ssim, feature_raw]

    if args.coco:
        generate_dice_score(total_loader, feature, 
                            ["spaghetti", "phikon_only"], args.name, 
                            args.save_dir, coco_L, do_crop=args.crop, do_invert=args.invert)
    else:
        if not os.path.isdir(os.path.join(args.save_dir, "visualization")):
            os.makedirs(os.path.join(args.save_dir, "visualization"))
        generate_visualization(total_loader, feature, args.save_dir, 
                               do_invert=args.invert, log_time=args.log_time)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--name', type=str, help='Name of the experiment')
    parser.add_argument('--crop', action="store_true", help="whether to crop your images")
    parser.add_argument('--ssim', type=str, 
                        help='path to ssim model')
    parser.add_argument('--image_path', type=str, nargs='+', help='Path(s) to the image')
    parser.add_argument('--save_dir', type=str, help='Path to save the visualization')
    parser.add_argument('--data_indices', type=str, nargs='+', 
                        help='Path(s) to the txt files containing indicies for data split')
    parser.add_argument('--coco', type=str, nargs='+', default=None, 
                        help='Path(s) to the COCO annotation file for segmentation')
    parser.add_argument('--invert', action="store_true",
                        help="Invert the image")
    parser.add_argument('--log_time', action="store_true",
                        help="Log the time for feature extraction")
    parser.add_argument('--gfp_data', action="store_true",
                        help="Use the gfp data")
    parser.add_argument('--gfp_data_russian', action="store_true",
                        help="Use the russian gfp data")
    args = parser.parse_args()
    print("Program starting with the following arguments:")
    print(args)

    os.makedirs(args.save_dir, exist_ok=True)

    main()
